[package]
name = "shydecoder"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["lib"]

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
glob = { version = "0.3.1" }


